---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/quotes":
    get:
      summary: list quotes
      responses:
        '200':
          description: successful
    post:
      summary: create quote
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                content:
                  type: string
  "/api/v1/quotes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quote
      responses:
        '200':
          description: successful
    patch:
      summary: update quote
      responses:
        '200':
          description: successful
    put:
      summary: update quote
      responses:
        '200':
          description: successful
    delete:
      summary: delete quote
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
